name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install jsonschema

    - name: Run Flask in the background
      run: |
        python -m flask run --host=0.0.0.0 --port=5000 &
        echo "Flask is running in the background"

    - name: Sleep for a while
      run: sleep 20s

    - name: Test Flask server
      run: |
        response_code=$(curl --write-out %{http_code} --silent --output /dev/null http://0.0.0.0:5000/validate-psi)
        if [ $response_code -ne 404 ]
        then
          echo "Flask server is not running correctly. HTTP response code: $response_code"
          exit 1
        else
          echo "Flask server is running correctly"
        fi
