name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Flask
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run Flask server
      run: |
        nohup python -m flask run --host=0.0.0.0 &

    - name: Wait for Flask
      run: |
        sleep 10

    - name: Test Flask
      run: |
        curl -I http://localhost:5000
