name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Flask
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Create basic Flask app
      run: |
        echo "from flask import Flask, jsonify" > app.py
        echo "app = Flask(__name__)" >> app.py
        echo "@app.route('/', methods=['GET'])" >> app.py
        echo "def home():" >> app.py
        echo "    return jsonify({'message': 'Hello, World!'}), 200" >> app.py

    - name: Run Flask server
      run: |
        export FLASK_APP=app.py
        nohup flask run --host=0.0.0.0 > flask.log 2>&1 &

    - name: Wait for Flask
      run: |
        sleep 10

    - name: Test Flask
      run: |
        curl -I http://localhost:5000
