name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      flask:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
          - 8080:80

    steps:
    - name: Wait for Flask
      run: sleep 10

    - name: Test Flask
      run: curl -I http://localhost:8080
