name: CI

on: [push, pull_request]

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    services:
      mock_rampage:
        image: python:3.8
        ports:
          - 5001:5001
        options: --entrypoint "flask --app ./mock_rampage/mock_rampage run -h mock_rampage -p 5001"
    steps:
      - name: Wait for mock_rampage to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5001/health; then
              echo 'mock_rampage is up'
              break
            else
              echo 'Waiting for mock_rampage...'
              sleep 1
            fi
          done
