name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      flask:
        image: python:3.8
        ports:
          - 5000:5000
        options: --name flask --entrypoint "flask run --host=0.0.0.0"
        volumes:
          - ${{ github.workspace }}:/app
        working_dir: /app
        env:
          FLASK_APP: app.py

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Flask
      run: |
        sleep 10

    - name: Test Flask
      run: |
        curl -I http://localhost:5000
